# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastclaude',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/fastclaude',
                'lib_path': 'fastclaude'},
  'syms': {'fastclaude.core': {'fastclaude.core.foo': ('core.html#foo', 'fastclaude/core.py')}}}
