"""`astream` and `ClaudeRun`: stateless completions through the installed Claude Code

`astream(msgs, ...)` returns a `ClaudeRun`: one stateless completion through the installed `claude`, using its login and subscription. The complete history (as `aidialog.msg_parts.Msg`s, ending with a real user prompt) is compiled into a native transcript via `fastclaude.session` under a fresh random session id and resumed; callable tools are served in-process via `fastclaude.protocol`; iteration yields the raw stream-json events; `.messages` accumulates the canonical trace (signatures intact, tool names unqualified) and `.result` the terminal result, so the next request can replay everything. `run.interrupt()` ends a turn natively, and closing the stream interrupts, drains, escalates to terminate/kill, and removes the transcript. Runs default to an isolated XDG cache work dir, so no real project's sessions or settings are touched; pass `cwd=` for project context, and `native_tools=` to enable built-ins such as `'WebSearch'`.

Docs: https://AnswerDotAI.github.io/fastclaude/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_core.ipynb.

# %% auto #0
__all__ = ['MCP_SERVER', 'MCP_PREFIX', 'SERVER_TOOLS', 'work_dir', 'compile_msgs', 'claude_cmd', 'claude_env', 'ClaudeRun',
           'astream']

# %% ../nbs/02_core.ipynb #326ece78
import asyncio, json, os, shutil, uuid
from contextlib import suppress
from fastcore.utils import *
from fastcore.meta import delegates
from fastcore.xdg import xdg_cache_home
from fastllm.anthropic import denorm_msgs, norm_parts
from aidialog.msg_parts import Msg, Text, ToolUse, ToolResult, Media
from .session import *
from .protocol import *

# %% ../nbs/02_core.ipynb #b5122707
MCP_SERVER = 'fastclaude'
MCP_PREFIX = f'mcp__{MCP_SERVER}__'
SERVER_TOOLS = ('WebSearch','WebFetch')

def work_dir():
    "The default run directory: an isolated pseudo-project under the XDG cache dir"
    p = xdg_cache_home()/'fastclaude'
    p.mkdir(parents=True, exist_ok=True)
    return p

# %% ../nbs/02_core.ipynb #7feb4c5d
def compile_msgs(
    msgs, # Complete history as `Msg`s, ending with a real user prompt
):
    "`(history, prompt)`: qualified wire messages for the transcript, and the live turn's content"
    msgs = listify(msgs)
    if not msgs: raise ValueError('empty message history')
    last = msgs[-1]
    if last.role!='user' or not any(isinstance(p, (Text,Media)) for p in last.content):
        raise ValueError('history must end with a user message containing a real prompt, not only tool results')
    den = denorm_msgs(msgs)
    return prefix_tools(den[:-1], MCP_PREFIX, skip=SERVER_TOOLS), den[-1]['content']

# %% ../nbs/02_core.ipynb #0c3b7a6a
def claude_cmd(
    model=None, # Model alias or full name; None uses the user's default
    resume=None, # Session id to resume, i.e. the transcript just written
    system=None, # System prompt; None keeps Claude Code's own
    tools=False, # Offer the private SDK MCP server?
    native_tools=(), # Built-in Claude Code tools to enable, e.g. 'WebSearch'
    allowed=(), # `--allowedTools` entries, e.g. qualified callable names
    claude_path=None, # Explicit claude executable; found on PATH if None
):
    "argv for one headless stream-json claude run"
    c = [str(claude_path or shutil.which('claude') or 'claude'), '--output-format','stream-json',
        '--input-format','stream-json', '--verbose', '--include-partial-messages']
    if model: c += ['--model', model]
    if system is not None: c += ['--system-prompt', system]
    if resume: c += [f'--resume={resume}']
    if tools: c += ['--mcp-config', json.dumps(dict(mcpServers={MCP_SERVER: dict(type='sdk', name=MCP_SERVER)}))]
    c.append('--strict-mcp-config')
    c += ['--tools', ','.join(native_tools)]
    if allowed: c += ['--allowedTools', ','.join(allowed)]
    return c

def claude_env():
    "A child environment that cannot bill an API key and does not think it is nested"
    env = dict(os.environ, ANTHROPIC_API_KEY='')
    env.pop('CLAUDECODE', None)
    return env

# %% ../nbs/02_core.ipynb #ad501dc1
class ClaudeRun:
    "One stateless completion: a fresh transcript, one claude process, streamed events, a canonical trace"
    def __init__(self,
        msgs, # Complete history as `Msg`s, ending with a real user prompt
        model='sonnet', # Model alias or full name
        system=None, # System prompt; None keeps Claude Code's own
        tools=None, # Callable tools, in either `tool_spec` form
        cwd=None, # Project directory for the run; the isolated `work_dir()` if None
        native_tools=(), # Built-in Claude Code tools to enable, e.g. 'WebSearch'
        claude_path=None, # Explicit claude executable; found on PATH if None
    ):
        store_attr()
        self.messages,self.result,self.proc,self.proto = [],None,None,None
        self._names,self._closed,self._spath = {},False,None

    def __aiter__(self):
        if not hasattr(self, '_it'): self._it = self._run()
        return self._it

@delegates(ClaudeRun)
def astream(msgs, **kwargs):
    "Start one stateless completion; iterate the returned `ClaudeRun` for its raw events"
    return ClaudeRun(msgs, **kwargs)

# %% ../nbs/02_core.ipynb #e5bc11c4
@patch
async def _spawn(self:ClaudeRun):
    "Compile and file the history, then start claude resuming it; returns the live turn's content"
    self.cwd = Path(self.cwd) if self.cwd else work_dir()
    hist,prompt = compile_msgs(self.msgs)
    sid = str(uuid.uuid4())
    if hist:
        save_sess(msgs2recs(hist, key=sid, cwd=self.cwd), sid, self.cwd)
        self._spath = sess_file(sid, self.cwd)
    schemas,_ = mk_tools(self.tools or [])
    allowed = [MCP_PREFIX+s['name'] for s in schemas] + list(self.native_tools)
    argv = claude_cmd(self.model, resume=sid if hist else None, system=self.system, tools=bool(schemas),
        native_tools=self.native_tools, allowed=allowed, claude_path=self.claude_path)
    self.proc = await asyncio.create_subprocess_exec(*argv, stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE, limit=2**25, cwd=self.cwd, env=claude_env())
    self.proto = ClaudeProto(self.proc, tools=self.tools, server=MCP_SERVER)
    return prompt

# %% ../nbs/02_core.ipynb #8d5f8fe6
def _unq(nm): return nm[len(MCP_PREFIX):] if nm and nm.startswith(MCP_PREFIX) else nm
def _flat(c): return c if isinstance(c, str) else '\n'.join(b.get('text','') for b in c if b.get('type')=='text')

@patch
def _track(self:ClaudeRun, m):
    "Fold one raw event into `.messages` and `.result`"
    t,c = m.get('type'), nested_idx(m, 'message', 'content')
    if t=='assistant' and isinstance(c, list):
        parts = norm_parts(m['message'])
        for p in parts:
            if isinstance(p, ToolUse): p.name = self._names[p.id] = _unq(p.name)
        self.messages.append(Msg('assistant', parts))
    elif t=='user' and isinstance(c, list) and c and all(b.get('type')=='tool_result' for b in c):
        self.messages.append(Msg('tool', [ToolResult(id=b.get('tool_use_id'), name=self._names.get(b.get('tool_use_id')),
            text=_flat(b.get('content',''))) for b in c]))
    elif t=='result': self.result = m

# %% ../nbs/02_core.ipynb #ea5dbde9
@patch
async def _kick(self:ClaudeRun, prompt):
    "Handshake, then the one live user turn"
    await self.proto.initialize()
    await self.proto.send(dict(type='user', message=dict(role='user', content=prompt)))

@patch
async def _run(self:ClaudeRun):
    "The event stream: spawn, kick off, yield raw events until the terminal result"
    prompt = await self._spawn()
    kick = asyncio.create_task(self._kick(prompt))
    try:
        async for m in self.proto.events():
            self._track(m)
            yield m
            if m.get('type')=='result': break
    finally:
        kick.cancel()
        await self.aclose()

@patch
async def interrupt(self:ClaudeRun, timeout=30):
    "Claude's native interrupt: end the current turn; the stream stays open to drain the aborted tail"
    return await self.proto.interrupt(timeout)

# %% ../nbs/02_core.ipynb #d1f78540
@patch
async def _drain(self:ClaudeRun, timeout=10):
    "Read the aborted turn's tail directly, resolving control responses and folding events into the trace"
    async def _go():
        async for m in read_msgs(self.proc.stdout):
            if m.get('type')=='control_response': self.proto._resolve(m)
            else: self._track(m)
            if m.get('type')=='result': return
    with suppress(Exception): await asyncio.wait_for(_go(), timeout)

@patch
async def _cleanup(self:ClaudeRun):
    p = self.proc
    if p and p.returncode is None:
        if self.result is None and p.stdin and not p.stdin.is_closing():
            t = asyncio.create_task(self._drain())
            with suppress(Exception): await asyncio.wait_for(self.proto.interrupt(), 5)
            await t
        with suppress(Exception): p.stdin.close()
        try: await asyncio.wait_for(p.wait(), 5)
        except (TimeoutError, asyncio.TimeoutError):
            with suppress(ProcessLookupError): p.terminate()
            try: await asyncio.wait_for(p.wait(), 5)
            except (TimeoutError, asyncio.TimeoutError):
                with suppress(ProcessLookupError): p.kill()
                with suppress(Exception): await p.wait()
    if self.proto: await self.proto.aclose()
    if self._spath: Path(self._spath).unlink(missing_ok=True)

@patch
async def aclose(self:ClaudeRun):
    "Interrupt if mid-turn, drain, close, escalate, and remove the transcript; idempotent and cancellation-shielded"
    if self._closed: return
    self._closed = True
    await asyncio.shield(asyncio.create_task(self._cleanup()))
