"""`astream` and `ClaudeRun`: stateless completions through the installed Claude Code

`astream(msgs, ...)` creates a `ClaudeRun` for one stateless completion through your installed `claude`. It uses Claude Code's login and subscription. Supply the complete conversation as `aidialog.msg_parts.Msg` objects on every request. FastClaude writes the history as a native transcript with `fastclaude.session` and starts a fresh process to resume it.

Your application executes the tools it supplies. When Claude requests one, the run ends with a `ToolUse`. Execute the tool and append its `ToolResult` to the history for the next request. FastClaude marks the pending call in the transcript. Its `fastclaude.protocol` bridge returns your result when Claude resumes that call.

Iterate the run for raw stream-json events. `run.messages` contains the generated `Msg` trace with thinking signatures intact and your original tool names. `run.result` contains the terminal result. Append the trace to your history for the next request.

Use `run.interrupt()` to end the current turn. Close the run to stop its process and remove its temporary transcript. Runs use a dedicated XDG cache work directory by default. Pass `cwd=` to use a project's context or `native_tools=` to enable Claude Code tools such as `WebSearch`.

Docs: https://AnswerDotAI.github.io/fastclaude/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_core.ipynb.

# %% auto #0
__all__ = ['MCP_SERVER', 'MCP_PREFIX', 'SERVER_TOOLS', 'work_dir', 'compile_msgs', 'claude_cmd', 'claude_env', 'ClaudeRun',
           'astream', 'unqual']

# %% ../nbs/02_core.ipynb #326ece78
import asyncio, json, os, shutil, uuid
from contextlib import suppress
from fastcore.utils import *
from fastcore.meta import delegates
from fastcore.xdg import xdg_cache_home
from fastllm.anthropic import denorm_msgs, norm_parts
from aidialog.msg_parts import Msg, Text, ToolUse, ToolResult, Media
from .session import *
from .protocol import *

# %% ../nbs/02_core.ipynb #b5122707
MCP_SERVER = 'fastclaude'
MCP_PREFIX = f'mcp__{MCP_SERVER}__'
SERVER_TOOLS = ('WebSearch','WebFetch')

def work_dir():
    "Create and return the shared FastClaude work directory under the XDG cache directory"
    p = xdg_cache_home()/'fastclaude'
    p.mkdir(parents=True, exist_ok=True)
    return p

# %% ../nbs/02_core.ipynb #7feb4c5d
def compile_msgs(
    msgs, # Complete history as `Msg`s, ending with a user prompt or with the tool results Claude asked for
):
    """Return `(history, prompt, deferred)` for a new run.

    `history` contains wire messages for the transcript. `prompt` is the live turn's content, or None for a continuation.
    `deferred` is the pending `(tool_use, tool_result)` pair, or None for a live prompt.
    """
    msgs = listify(msgs)
    if not msgs: raise ValueError('empty message history')
    den = prefix_tools(denorm_msgs(msgs), MCP_PREFIX, skip=SERVER_TOOLS)
    lc = den[-1]['content']
    if msgs[-1].role=='user' and any(isinstance(p, (Text,Media)) for p in msgs[-1].content): return den[:-1], lc, None
    if den[-1]['role']=='user' and isinstance(lc, list) and lc and all(b.get('type')=='tool_result' for b in lc):
        tus = {b['id']: b for m in den for b in (m['content'] if isinstance(m['content'], list) else []) if b.get('type')=='tool_use'}
        pend = [tus.get(b['tool_use_id']) for b in lc]
        if None in pend: raise ValueError('a trailing tool result answers no tool_use in the history')
        hist = den[:-1] + ([dict(role='user', content=lc[:-1])] if len(lc)>1 else [])
        return hist, None, (pend[-1], lc[-1])
    raise ValueError('history must end with a user prompt or tool results')

# %% ../nbs/02_core.ipynb #0c3b7a6a
def claude_cmd(
    model=None, # Model alias or full name; None uses the user's default
    resume=None, # Session id to resume, i.e. the transcript just written
    system=None, # System prompt; None keeps Claude Code's own
    tools=False, # Offer the private SDK MCP server?
    native_tools=(), # Built-in Claude Code tools to enable, e.g. 'WebSearch'
    allowed=(), # `--allowedTools` entries, e.g. qualified callable names
    append_system=None, # Text appended to Claude Code's own system prompt, which stays
    setting_sources=None, # Settings that load, e.g. ['project']; () loads none; None keeps the CLI default (all)
    mcp_config=None, # Extra MCP server entries, e.g. `dict(clikernel=dict(type='stdio', command=...))`
    max_turns=None, # Bound on agent turns; None is unbounded
    max_budget=None, # Max USD for the run; None is unbounded
    permission_mode=None, # e.g. 'bypassPermissions'; None keeps the CLI default
    thinking=None, # 'adaptive' or 'disabled'; None keeps the CLI default
    effort=None, # Thinking effort: 'low', 'medium', or 'high'
    claude_path=None, # Explicit claude executable; found on PATH if None
):
    "Build argv for one headless stream-json Claude Code run"
    c = [str(claude_path or shutil.which('claude') or 'claude'), '--output-format','stream-json',
        '--input-format','stream-json', '--verbose', '--include-partial-messages']
    if model: c += ['--model', model]
    if system is not None: c += ['--system-prompt', system]
    if append_system: c += ['--append-system-prompt', append_system]
    if resume: c += [f'--resume={resume}']
    servers = dict(mcp_config or {})
    if tools: servers[MCP_SERVER] = dict(type='sdk', name=MCP_SERVER)
    if servers: c += ['--mcp-config', json.dumps(dict(mcpServers=servers))]
    c.append('--strict-mcp-config')
    c += ['--tools', ','.join(native_tools)]
    if allowed: c += ['--allowedTools', ','.join(allowed)]
    if setting_sources is not None: c.append(f"--setting-sources={','.join(setting_sources)}")
    for f,v in (('--max-turns',max_turns), ('--max-budget-usd',max_budget), ('--permission-mode',permission_mode), ('--thinking',thinking), ('--effort',effort)):
        if v is not None: c += [f, str(v)]
    return c

def claude_env():
    "Copy the environment with an empty `ANTHROPIC_API_KEY` and no `CLAUDECODE`"
    env = dict(os.environ, ANTHROPIC_API_KEY='')
    env.pop('CLAUDECODE', None)
    return env

# %% ../nbs/02_core.ipynb #ad501dc1
class ClaudeRun:
    "Manage one Claude Code process for a stateless completion with streamed events and a reusable message trace"
    @delegates(claude_cmd, but=['model','resume','tools','native_tools','allowed'])
    def __init__(self,
        msgs, # Complete history as `Msg`s, ending with a user prompt or the tool results Claude asked for
        model='sonnet', # Model alias or full name
        tools=None, # Tool schemas to advertise, in either `tool_spec` form; the caller executes
        cwd=None, # Project directory for the run; the shared `work_dir()` if None
        native_tools=(), # Built-in Claude Code tools to enable, e.g. 'WebSearch'
        allowed=(), # Extra `--allowedTools` entries beyond the advertised schemas
        env=None, # Extra child environment variables, merged over `claude_env()`
        **kwargs, # Passed to `claude_cmd`, e.g. `system`, `setting_sources`, `mcp_config`
    ):
        store_attr('msgs,model,tools,cwd,native_tools,allowed,env')
        self.cmd_kwargs = kwargs
        self.messages,self.result,self.proc,self.proto = [],None,None,None
        self._names,self._closed,self._spath,self._deferred = {},False,None,None

    def __aiter__(self):
        if not hasattr(self, '_it'): self._it = self._run()
        return self._it

@delegates(ClaudeRun)
def astream(msgs, **kwargs):
    "Create a `ClaudeRun` for one stateless completion and iterate it for raw events"
    return ClaudeRun(msgs, **kwargs)

# %% ../nbs/02_core.ipynb #e5bc11c4
@patch
async def _spawn(self:ClaudeRun):
    """Write the transcript and start Claude Code.

    Return the live prompt content, or None for a continuation.
    """
    self.cwd = Path(self.cwd).expanduser() if self.cwd else work_dir()
    hist,prompt,deferred = compile_msgs(self.msgs)
    sid = str(uuid.uuid4())
    recs = msgs2recs(hist, key=sid, cwd=self.cwd)
    held = None
    if deferred:
        tu,tr = deferred
        recs.append(mk_deferred(tu, cwd=self.cwd))
        held,self._deferred = tool_reply(tr.get('content',''), tr.get('is_error', False)),tu['id']
    if recs:
        save_sess(recs, sid, self.cwd)
        self._spath = sess_file(sid, self.cwd)
    schemas = mk_tools(self.tools or [])
    allowed = [MCP_PREFIX+s['name'] for s in schemas] + list(self.native_tools) + list(self.allowed)
    argv = claude_cmd(self.model, resume=sid if recs else None, tools=bool(schemas),
        native_tools=self.native_tools, allowed=allowed, **self.cmd_kwargs)
    if not shutil.which(argv[0]):
        await self.aclose()
        raise FileNotFoundError(f"claude executable not found: {argv[0]}")
    self.proc = await asyncio.create_subprocess_exec(*argv, stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE, limit=2**25, cwd=self.cwd, env=dict(claude_env(), **(self.env or {})))
    self.proto = ClaudeProto(self.proc, tools=self.tools, held=held, server=MCP_SERVER)
    return prompt

# %% ../nbs/02_core.ipynb #8d5f8fe6
def unqual(nm):
    "Remove the `mcp__fastclaude__` prefix from `nm` when present"
    return nm[len(MCP_PREFIX):] if nm and nm.startswith(MCP_PREFIX) else nm

def _flat(c): return c if isinstance(c, str) else '\n'.join(b.get('text','') for b in c if b.get('type')=='text')

@patch
def _track(self:ClaudeRun, m):
    "Update `.messages` or `.result` from one raw event"
    t,c = m.get('type'), nested_idx(m, 'message', 'content')
    if t=='assistant' and isinstance(c, list):
        parts = norm_parts(m['message'])
        for p in parts:
            if isinstance(p, ToolUse): p.name = self._names[p.id] = unqual(p.name)
        self.messages.append(Msg('assistant', parts))
    elif t=='user' and isinstance(c, list) and c and all(b.get('type')=='tool_result' for b in c):
        if any(b.get('tool_use_id')==self._deferred for b in c): return
        self.messages.append(Msg('tool', [ToolResult(id=b.get('tool_use_id'), name=self._names.get(b.get('tool_use_id')),
            text=_flat(b.get('content',''))) for b in c]))
    elif t=='result': self.result = m

# %% ../nbs/02_core.ipynb #ea5dbde9
@patch
async def _kick(self:ClaudeRun, prompt):
    "Complete the handshake and send the live prompt if present"
    await self.proto.initialize()
    if prompt is not None: await self.proto.send(dict(type='user', message=dict(role='user', content=prompt)))

# %% ../nbs/02_core.ipynb #ce7d4c70
@patch
async def _run(self:ClaudeRun):
    "Start Claude Code and yield raw events through its terminal result"
    prompt = await self._spawn()
    kick = asyncio.create_task(self._kick(prompt))
    try:
        async for m in self.proto.events():
            self._track(m)
            yield m
            if m.get('type')=='result': break
    finally:
        kick.cancel()
        await self.aclose()

# %% ../nbs/02_core.ipynb #274024f8
@patch
async def interrupt(self:ClaudeRun, timeout=30):
    "Ask Claude Code to end the turn while keeping the stream open for remaining events"
    return await self.proto.interrupt(timeout)

# %% ../nbs/02_core.ipynb #a64794c5
async def _wait_process(proc, timeout=5):
    try:
        await asyncio.wait_for(proc.wait(), timeout)
        return True
    except (TimeoutError, asyncio.TimeoutError): return False

# %% ../nbs/02_core.ipynb #20690c2c
async def _reap_process(proc):
    if await _wait_process(proc): return
    with suppress(ProcessLookupError): proc.terminate()
    if await _wait_process(proc): return
    with suppress(ProcessLookupError): proc.kill()
    with suppress(Exception): await proc.wait()

# %% ../nbs/02_core.ipynb #6e60c0aa
@patch
async def _cleanup(self:ClaudeRun):
    p = self.proc
    if p and p.returncode is None:
        with suppress(Exception): p.stdin.close()
        await _reap_process(p)
    if self.proto: await self.proto.aclose()
    if self._spath: Path(self._spath).unlink(missing_ok=True)

# %% ../nbs/02_core.ipynb #9acc7b5c
@patch
async def aclose(self:ClaudeRun):
    """Close stdin, stop the process, and remove the transcript.

    Start cleanup once and shield it from cancellation.
    """
    if self._closed: return
    self._closed = True
    await asyncio.shield(asyncio.create_task(self._cleanup()))
