"""Claude Code's stream-json wire protocol: NDJSON transport, control routing, and the deferred-tool bridge

Speak Claude Code's stream-json wire protocol directly, with no Agent SDK: `read_msgs` frames NDJSON from a piped process, `mk_tools` turns annotated callables or schema dicts into the tool list to advertise, `hold_result` queues an already-known tool result for Claude to collect, `mcp_dispatch` implements the MCP-shaped JSON-RPC methods the CLI uses to list tools and fetch held results, and `ClaudeProto` is the per-process peer: it matches `control_response`s to pending requests, runs each incoming `control_request` as its own cancellable task, routes `PreToolUse` hook callbacks (a call with a held result is allowed, everything else defers, ending the turn so the caller can execute), answers `control_cancel_request` by cancelling and staying silent, and yields every other message through untouched. `initialize` and `interrupt` are ordinary control requests. Tools are never executed here: the caller owns the tool loop, and the runner in `fastclaude.core` owns the process itself.

Docs: https://AnswerDotAI.github.io/fastclaude/protocol.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_protocol.ipynb.

# %% auto #0
__all__ = ['read_msgs', 'tool_spec', 'mk_tools', 'tool_reply', 'hold_result', 'jrpc', 'mcp_dispatch', 'ctrl_req', 'ctrl_ok',
           'ctrl_err', 'ClaudeProto']

# %% ../nbs/01_protocol.ipynb #01d59d89
import asyncio, json, os
from fastcore.utils import *
from fastcore.funccall import get_schema
from .session import canon

# %% ../nbs/01_protocol.ipynb #81bd6eea
async def read_msgs(
    stream, # An asyncio `StreamReader` of NDJSON, e.g. a claude process's stdout
):
    "Decoded messages from `stream`, one per line; blank lines skip, non-JSON raises, a truncated final fragment drops"
    while line := await stream.readline():
        if not (s := line.strip()): continue
        try: yield json.loads(s)
        except json.JSONDecodeError as e:
            if line.endswith(b'\n'): raise ValueError(f'bad NDJSON line: {s[:200]!r}') from e
            return  # no newline: a producer killed mid-write; the fragment is unrecoverable

# %% ../nbs/01_protocol.ipynb #936b255f
def tool_spec(
    t, # An annotated callable, or a schema dict with `name`, `description`, `inputSchema`
):
    "The schema dict for one tool; a callable's schema is derived from its signature, and the callable is never executed"
    return get_schema(t, pname='inputSchema') if callable(t) else t

def mk_tools(
    tools, # Tools in either `tool_spec` form
):
    "The schema list to advertise for `tools`"
    return [tool_spec(t) for t in listify(tools)]

# %% ../nbs/01_protocol.ipynb #1e3b35d0
def tool_reply(content, is_error=False):
    "An MCP tool return value carrying an Anthropic `tool_result`'s `content`"
    if isinstance(content, str): content = [dict(type='text', text=content)]
    def _cvt(b):
        if b.get('type')!='image': return b
        s = b['source']
        return dict(type='image', data=s['data'], mimeType=s['media_type'])
    return dict(content=[_cvt(b) for b in content], isError=is_error)

def _res_key(name, input): return canon([name, canon(dict(input))])

def hold_result(
    held, # The store to add to, a dict of queues
    name, # Qualified tool name, e.g. 'mcp__fastclaude__flux_meter'
    input, # The call's arguments, matched canonically
    content, # The known result: an Anthropic `tool_result`'s `content`
    is_error=False, # Was the result an error?
):
    "Queue a result for the bridge to serve when Claude re-invokes `name` with `input`; returns `held`"
    held.setdefault(_res_key(name, input), []).append(tool_reply(content, is_error))
    return held

# %% ../nbs/01_protocol.ipynb #b9d786b4
def jrpc(
    method, # JSON-RPC method name
    id=None, # Request id; None makes a notification
    **params, # The call's `params`, omitted when empty
):
    "One JSON-RPC message, e.g. what the CLI sends our bridge"
    r = dict(jsonrpc='2.0', id=id, method=method)
    if id is None: r.pop('id')
    if params: r['params'] = params
    return r

# %% ../nbs/01_protocol.ipynb #6fea8305
def mcp_dispatch(
    msg, # One JSON-RPC message from the CLI
    schemas, # Tool schemas to advertise, from `mk_tools`
    held, # Held results from `hold_result`, keyed by qualified name and arguments
    server='fastclaude', # Server name reported to the CLI, qualifying the held keys
):
    "The JSON-RPC response for `msg`, or None for a notification"
    m,i = msg.get('method'), msg.get('id')
    def res(r): return dict(jsonrpc='2.0', id=i, result=r)
    if m == 'initialize':
        pv = nested_idx(msg, 'params', 'protocolVersion') or '2024-11-05'
        return res(dict(protocolVersion=pv, capabilities=dict(tools={}), serverInfo=dict(name=server, version='1.0')))
    if m and m.startswith('notifications/'): return None
    if m == 'ping': return res({})
    if m == 'tools/list': return res(dict(tools=schemas))
    if m == 'tools/call':
        nm,args = nested_idx(msg, 'params', 'name'), nested_idx(msg, 'params', 'arguments') or {}
        q = held.get(_res_key(f'mcp__{server}__{nm}', args))
        if not q: return res(dict(content=[dict(type='text', text=f'no held result for {nm}')], isError=True))
        return res(q.pop(0))
    return dict(jsonrpc='2.0', id=i, error=dict(code=-32601, message=f'method not found: {m}'))

# %% ../nbs/01_protocol.ipynb #e51c5e88
def ctrl_req(rid, **req):
    "A `control_request` envelope"
    return dict(type='control_request', request_id=rid, request=req)

def ctrl_ok(rid, **resp):
    "A success `control_response` envelope"
    return dict(type='control_response', response=dict(subtype='success', request_id=rid, response=resp))

def ctrl_err(rid, error):
    "An error `control_response` envelope"
    return dict(type='control_response', response=dict(subtype='error', request_id=rid, error=str(error)))

# %% ../nbs/01_protocol.ipynb #00be1e4d
class ClaudeProto:
    "Control-protocol peer for one claude process: request matching, hook routing, held-result serving, passthrough events"
    def __init__(self,
        proc, # An asyncio subprocess speaking stream-json on piped stdin/stdout
        tools=None, # Tool schemas to advertise, in either `tool_spec` form
        held=None, # Held results from `hold_result`; calls without one defer
        server='fastclaude', # SDK MCP server name, matching the `--mcp-config` entry
    ):
        self.proc,self.held,self.server = proc,held or {},server
        self.schemas = mk_tools(tools or [])
        self._lock,self._n,self._pending,self._inflight = asyncio.Lock(),0,{},{}

    async def send(self, obj):
        "Write one JSON message to claude's stdin"
        async with self._lock:
            self.proc.stdin.write(json.dumps(obj, ensure_ascii=False).encode()+b'\n')
            await self.proc.stdin.drain()

    async def send_req(self, req, timeout=60):
        "Send a control request, await its response by id, and return the inner `response` dict"
        self._n += 1
        rid = f'req_{self._n}_{os.urandom(4).hex()}'
        fut = asyncio.get_running_loop().create_future()
        self._pending[rid] = fut
        await self.send(ctrl_req(rid, **req))
        try: return await asyncio.wait_for(fut, timeout)
        finally: self._pending.pop(rid, None)

    async def initialize(self, timeout=120):
        "The control-protocol handshake, registering the defer hook when tools are advertised"
        hooks = None
        if self.schemas:
            matcher = '|'.join(f"mcp__{self.server}__{s['name']}" for s in self.schemas)
            hooks = dict(PreToolUse=[dict(matcher=matcher, hookCallbackIds=['defer'])])
        return await self.send_req(dict(subtype='initialize', hooks=hooks), timeout)

    async def interrupt(self, timeout=30):
        "Claude's native interrupt: end the current turn, keeping the process alive"
        return await self.send_req(dict(subtype='interrupt'), timeout)

# %% ../nbs/01_protocol.ipynb #2f1ac188
@patch
def _resolve(self:ClaudeProto, msg):
    "Complete the pending request a `control_response` answers"
    r = msg.get('response') or {}
    if (fut := self._pending.get(r.get('request_id'))) and not fut.done():
        if r.get('subtype')=='error': fut.set_exception(RuntimeError(r.get('error') or 'control request failed'))
        else: fut.set_result(r.get('response') or {})

@patch
def _route(self:ClaudeProto, req):
    "The `PreToolUse` decision: a call with a held result is allowed, everything else defers"
    inp = req.get('input') or {}
    dec = 'allow' if self.held.get(_res_key(inp.get('tool_name'), inp.get('tool_input') or {})) else 'defer'
    return dict(hookSpecificOutput=dict(hookEventName='PreToolUse', permissionDecision=dec))

@patch
async def _handle(self:ClaudeProto, rid, req):
    "Answer one CLI-originated control request; cancelled handlers answer nothing"
    try:
        st = req.get('subtype')
        if st=='mcp_message': resp = dict(mcp_response=mcp_dispatch(req.get('message') or {}, self.schemas, self.held, self.server) or dict(jsonrpc='2.0', result={}))
        elif st=='hook_callback': resp = self._route(req)
        else: raise ValueError(f"unsupported control request: {st}")
        await self.send(ctrl_ok(rid, **resp))
    except asyncio.CancelledError: raise
    except Exception as e: await self.send(ctrl_err(rid, e))

# %% ../nbs/01_protocol.ipynb #57c71845
@patch
async def events(self:ClaudeProto):
    "Non-control messages from claude, with control traffic routed internally"
    try:
        async for m in read_msgs(self.proc.stdout):
            t = m.get('type')
            if t=='control_response': self._resolve(m)
            elif t=='control_request':
                rid = m.get('request_id')
                task = asyncio.create_task(self._handle(rid, m.get('request') or {}))
                self._inflight[rid] = task
                task.add_done_callback(lambda _,rid=rid: self._inflight.pop(rid, None))
            elif t=='control_cancel_request':
                if task := self._inflight.pop(m.get('request_id'), None): task.cancel()
            else: yield m
    finally: await self.aclose()


# %% ../nbs/01_protocol.ipynb #ec8d05d9
@patch
async def aclose(self:ClaudeProto):
    "Cancel in-flight handlers and pending requests; the process itself is the runner's to reap"
    for t in list(self._inflight.values()): t.cancel()
    for f in self._pending.values():
        if not f.done(): f.cancel()
