"""Claude Code's stream-json wire protocol: NDJSON transport, control routing, and the callable-tool bridge

Speak Claude Code's stream-json wire protocol directly, with no Agent SDK: `read_msgs` frames NDJSON from a piped process, `mk_tools` turns annotated callables or `(schema, callable)` pairs into an advertised tool list and a dispatch namespace, `mcp_dispatch` implements the five MCP-shaped JSON-RPC methods the CLI uses for in-process tools, and `ClaudeProto` is the per-process peer: it matches `control_response`s to pending requests, runs each incoming `control_request` as its own cancellable task, answers `control_cancel_request` by cancelling and staying silent, and yields every other message through untouched. `initialize` and `interrupt` are ordinary control requests. The runner in `fastclaude.core` owns the process itself: command line, environment, transcript, and cleanup.

Docs: https://AnswerDotAI.github.io/fastclaude/protocol.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_protocol.ipynb.

# %% auto #0
__all__ = ['read_msgs', 'tool_spec', 'mk_tools', 'tool_content', 'mcp_dispatch', 'ClaudeProto']

# %% ../nbs/01_protocol.ipynb #01d59d89
import asyncio, json, os
from fastcore.utils import *
from fastcore.funccall import get_schema, call_func, call_func_async

# %% ../nbs/01_protocol.ipynb #81bd6eea
async def read_msgs(
    stream, # An asyncio `StreamReader` of NDJSON, e.g. a claude process's stdout
):
    "Decoded messages from `stream`, one per line; blank lines skip, non-JSON raises, a truncated final fragment drops"
    while line := await stream.readline():
        if not (s := line.strip()): continue
        try: yield json.loads(s)
        except json.JSONDecodeError as e:
            if line.endswith(b'\n'): raise ValueError(f'bad NDJSON line: {s[:200]!r}') from e
            return  # no newline: a producer killed mid-write; the fragment is unrecoverable

# %% ../nbs/01_protocol.ipynb #936b255f
def tool_spec(
    t, # An annotated callable, or an explicit `(schema, callable)` pair
):
    "`(schema, callable)` for one tool; a callable's schema is derived from its signature"
    if callable(t): return get_schema(t, pname='inputSchema'), t
    return t

def mk_tools(
    tools, # Tools in either `tool_spec` form
):
    "`(schemas, ns)` for `tools`: the schema list to advertise, and the dispatch namespace"
    specs = [tool_spec(t) for t in listify(tools)]
    return [s for s,_ in specs], {s['name']: f for s,f in specs}

# %% ../nbs/01_protocol.ipynb #0b75d5a4
def tool_content(
    v, # A callable tool's return value
):
    "MCP `content` list for `v`: text for a str, empty for None, readable JSON otherwise"
    if v is None: return []
    if not isinstance(v, str): v = json.dumps(v, ensure_ascii=False, default=str)
    return [dict(type='text', text=v)]

# %% ../nbs/01_protocol.ipynb #6fea8305
async def mcp_dispatch(
    msg, # One JSON-RPC message from the CLI
    schemas, # Tool schemas to advertise, from `mk_tools`
    ns, # Dispatch namespace, from `mk_tools`
    server='fastclaude', # Server name reported to the CLI
):
    "The JSON-RPC response for `msg`, or None for a notification; a sync tool runs in a worker thread"
    m,i = msg.get('method'), msg.get('id')
    def res(r): return dict(jsonrpc='2.0', id=i, result=r)
    if m == 'initialize':
        pv = nested_idx(msg, 'params', 'protocolVersion') or '2024-11-05'
        return res(dict(protocolVersion=pv, capabilities=dict(tools={}), serverInfo=dict(name=server, version='1.0')))
    if m and m.startswith('notifications/'): return None
    if m == 'ping': return res({})
    if m == 'tools/list': return res(dict(tools=schemas))
    if m == 'tools/call':
        nm,args = nested_idx(msg, 'params', 'name'), nested_idx(msg, 'params', 'arguments') or {}
        try:
            if asyncio.iscoroutinefunction(ns.get(nm)): v = await call_func_async(nm, args, ns)
            else: v = await asyncio.to_thread(call_func, nm, args, ns)
            return res(dict(content=tool_content(v), isError=False))
        except asyncio.CancelledError: raise
        except Exception as e: return res(dict(content=[dict(type='text', text=f'{type(e).__name__}: {e}')], isError=True))
    return dict(jsonrpc='2.0', id=i, error=dict(code=-32601, message=f'method not found: {m}'))

# %% ../nbs/01_protocol.ipynb #00be1e4d
class ClaudeProto:
    "Control-protocol peer for one claude process: request matching, tool routing, passthrough events"
    def __init__(self,
        proc, # An asyncio subprocess speaking stream-json on piped stdin/stdout
        tools=None, # Tools in either `tool_spec` form
        server='fastclaude', # SDK MCP server name, matching the `--mcp-config` entry
    ):
        self.proc,self.server = proc,server
        self.schemas,self.ns = mk_tools(tools or [])
        self._lock,self._n,self._pending,self._inflight = asyncio.Lock(),0,{},{}

    async def send(self, obj):
        "Write one JSON message to claude's stdin"
        async with self._lock:
            self.proc.stdin.write(json.dumps(obj, ensure_ascii=False).encode()+b'\n')
            await self.proc.stdin.drain()

    async def send_req(self, req, timeout=60):
        "Send a control request, await its response by id, and return the inner `response` dict"
        self._n += 1
        rid = f'req_{self._n}_{os.urandom(4).hex()}'
        fut = asyncio.get_running_loop().create_future()
        self._pending[rid] = fut
        await self.send(dict(type='control_request', request_id=rid, request=req))
        try: return await asyncio.wait_for(fut, timeout)
        finally: self._pending.pop(rid, None)

    async def initialize(self, timeout=120):
        "The control-protocol handshake; claude answers nothing else until it completes"
        return await self.send_req(dict(subtype='initialize', hooks=None), timeout)

    async def interrupt(self, timeout=30):
        "Claude's native interrupt: end the current turn, keeping the process alive"
        return await self.send_req(dict(subtype='interrupt'), timeout)

# %% ../nbs/01_protocol.ipynb #2f1ac188
@patch
def _resolve(self:ClaudeProto, msg):
    "Complete the pending request a `control_response` answers"
    r = msg.get('response') or {}
    if (fut := self._pending.get(r.get('request_id'))) and not fut.done():
        if r.get('subtype')=='error': fut.set_exception(RuntimeError(r.get('error') or 'control request failed'))
        else: fut.set_result(r.get('response') or {})

@patch
async def _handle(self:ClaudeProto, rid, req):
    "Answer one CLI-originated control request; cancelled handlers answer nothing"
    try:
        if req.get('subtype')!='mcp_message': raise ValueError(f"unsupported control request: {req.get('subtype')}")
        r = await mcp_dispatch(req.get('message') or {}, self.schemas, self.ns, self.server)
        if r is None: r = dict(jsonrpc='2.0', result={})
        await self.send(dict(type='control_response', response=dict(subtype='success', request_id=rid, response=dict(mcp_response=r))))
    except asyncio.CancelledError: raise
    except Exception as e: await self.send(dict(type='control_response', response=dict(subtype='error', request_id=rid, error=str(e))))

# %% ../nbs/01_protocol.ipynb #57c71845
@patch
async def events(self:ClaudeProto):
    "Non-control messages from claude, with control traffic routed internally"
    try:
        async for m in read_msgs(self.proc.stdout):
            t = m.get('type')
            if t=='control_response': self._resolve(m)
            elif t=='control_request':
                rid = m.get('request_id')
                task = asyncio.create_task(self._handle(rid, m.get('request') or {}))
                self._inflight[rid] = task
                task.add_done_callback(lambda _,rid=rid: self._inflight.pop(rid, None))
            elif t=='control_cancel_request':
                if task := self._inflight.pop(m.get('request_id'), None): task.cancel()
            else: yield m
    finally: await self.aclose()


# %% ../nbs/01_protocol.ipynb #ec8d05d9
@patch
async def aclose(self:ClaudeProto):
    "Cancel in-flight handlers and pending requests; the process itself is the runner's to reap"
    for t in list(self._inflight.values()): t.cancel()
    for f in self._pending.values():
        if not f.done(): f.cancel()
