"""Read, write, and build native Claude Code session transcripts

## Session layout

Claude Code stores each conversation as JSONL at `~/.claude/projects/<dir>/<session-id>.jsonl`. `<dir>` is the resolved project path with every non-alphanumeric character replaced by `-`, including underscores. On macOS, a project in `/tmp/foo` therefore appears under `-private-tmp-foo`. `sess_dir` and `sess_file` compute these paths. A transcript is named by the conversation's first session id. `claude --resume` and post-compaction restarts can advertise a fresh id in `CLAUDE_CODE_SESSION_ID` while appending records to the original file, so the environment variable may name an id with no file behind it. `cur_sess` finds the project's most recently modified transcript.

Each line is one JSON object. The main fields are `type`, `uuid`, `parentUuid`, `sessionId`, `timestamp`, and `message`. Conversation records are `user` and `assistant`; a tool result is a `user` record containing `tool_result` blocks. The active conversation is the `parentUuid` chain walked back from the last record by `sess_thread`. `load_sess` and `load_recs` read every record, and `rec_txt` extracts each record's readable text.

## Building sessions

Resume does not care who wrote the file: a transcript assembled by hand resumes like any other. `mk_rec` fills one record's envelope, `save_sess` and `append_sess` chain and write records, and `msgs2recs`/`msgs2sess` convert whole Anthropic-style message lists into resumable sessions, deterministically when given a key. `mk_tu`, `mk_tr`, and `tool_turn` build synthetic tool exchanges, and `prefix_tools` qualifies caller tool names the way Claude Code records them.

Reading functions do not modify transcripts. `save_sess` and `append_sess` do: read their docs and inspect the target records before calling them; `save_sess` replaces a whole session file. `llmsurgery` builds on this module for finding, searching, curating, converting, and compacting sessions.

Docs: https://AnswerDotAI.github.io/fastclaude/session.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_session.ipynb.

# %% auto #0
__all__ = ['SESSIONS', 'ant_data', 'CC_VERSION', 'sess_dir', 'cur_sess', 'uniq_path', 'sess_file', 'load_recs', 'sess_thread',
           'rec_txt', 'canon', 'stable_uuid', 'mk_rec', 'save_sess', 'append_sess', 'msgs2recs', 'msgs2sess', 'sess_id',
           'fork_session', 'mk_tu', 'mk_tr', 'tool_turn', 'mk_deferred', 'load_sess', 'prefix_tools']

# %% ../nbs/00_session.ipynb #4ca88f98
import json, os, re, uuid
from datetime import datetime, timezone
from importlib.resources import files
from fastcore.utils import *
from fastcore.meta import delegates

# %% ../nbs/00_session.ipynb #c7311950
SESSIONS = Path.home()/'.claude'/'projects'

def sess_dir(
    cwd=None, # Project directory; the current directory if None
):
    "The folder where Claude Code keeps session transcripts for the project at `cwd`"
    return SESSIONS/re.sub(r'[^a-zA-Z0-9]', '-', str(Path(cwd or '.').expanduser().resolve()))

# %% ../nbs/00_session.ipynb #1037e744
def cur_sess(
    cwd=None, # Project directory; the current directory if None
):
    "The current conversation's session id: the most recent transcript for the project at `cwd`, else the advertised id"
    try: return max(sess_dir(cwd).glob('*.jsonl'), key=lambda p: p.stat().st_mtime).stem
    except ValueError: return os.environ.get('CLAUDE_CODE_SESSION_ID')

# %% ../nbs/00_session.ipynb #b99b3b4e
def uniq_path(
    paths, # Candidate paths, e.g. from a glob
    ref, # The reference they were matched against, for the error message
):
    "The single path in `paths`, or None if there are none; raises if `ref` is ambiguous"
    res = sorted({str(o) for o in paths})
    if len(res)>1: raise ValueError(f'{ref!r} matches {len(res)} sessions:\n' + '\n'.join(res))
    return Path(res[0]) if res else None

# %% ../nbs/00_session.ipynb #5e24a7c3
def sess_file(
    sid=None, # Session id or unique id prefix; `cur_sess(cwd)` if None
    cwd=None, # Project directory; the current directory, then all projects, if None
):
    "Path to the transcript of session `sid` for the project at `cwd`"
    sid = sid or cur_sess(cwd)
    p = sess_dir(cwd)/f'{sid}.jsonl'
    if p.exists(): return p
    root,pat = (sess_dir(cwd),f'{sid}*.jsonl') if cwd is not None else (SESSIONS,f'*/{sid}*.jsonl')
    return uniq_path(root.glob(pat), sid) or p

# %% ../nbs/00_session.ipynb #379f7285
def load_recs(path):
    "Session records read directly from JSONL `path`"
    return dict2obj(Path(path).read_jsonl())

# %% ../nbs/00_session.ipynb #bb9399a6
ant_data = Path(files('fastclaude')/'data'/'ant')

# %% ../nbs/00_session.ipynb #e1ee325a
def sess_thread(
    recs, # Session records, e.g. from `load_sess`
):
    "The records on the active conversation chain, walking `parentUuid` back from the last record"
    recs = L(r for r in recs if r.get('type') in ('user','assistant','attachment','system') and r.get('uuid'))
    byid = {r.uuid:r for r in recs}
    cur,res,seen = recs[-1],[],set()
    while cur is not None:
        if cur.uuid in seen: raise ValueError(f'parentUuid cycle at record uuid {cur.uuid}')
        seen.add(cur.uuid)
        res.append(cur)
        cur = byid.get(cur.get('parentUuid'))
    return L(reversed(res))

# %% ../nbs/00_session.ipynb #4bb05266
def _txts(o, skip=()):
    if isinstance(o, str): yield o
    elif isinstance(o, dict): yield from (t for k,v in o.items() if k not in skip for t in _txts(v, skip))
    elif is_listy(o): yield from (t for x in o for t in _txts(x, skip))

# %% ../nbs/00_session.ipynb #d7985a13
def rec_txt(
    r, # A session record
):
    "Every readable string in `r`'s message content, joined, for finding records by text"
    return '\n'.join(_txts(obj2dict(r).get('message', {}).get('content', ''), skip=('type','id','tool_use_id','signature')))

# %% ../nbs/00_session.ipynb #44743a5a
CC_VERSION = '2.1.223'

def canon(o):
    "Canonical compact JSON for `o`, key-sorted, for stable hashing"
    return json.dumps(o, sort_keys=True, separators=(',', ':'), ensure_ascii=False)

def stable_uuid(s):
    "A uuid deterministically derived from string `s`"
    return str(uuid.uuid5(uuid.NAMESPACE_URL, s))

# %% ../nbs/00_session.ipynb #13e1128d
def _now(): return datetime.now(timezone.utc).strftime(r'%Y-%m-%dT%H:%M:%S.%f')[:-3]+'Z'

def _est_toks(o):
    "Rule-of-thumb token estimate for every string in `o`: words * 1.5"
    return int(sum(len(s.split()) for s in _txts(o))*1.5)

# %% ../nbs/00_session.ipynb #3453820f
def mk_rec(
    role, # 'user' or 'assistant'
    content, # A string, or a list of content blocks
    cwd='.', # Project directory recorded in the envelope
    uid=None, # Record uuid; random if None
    ts=None, # ISO8601 timestamp; the current time if None
    model='claude-sonnet-4-6', # Recorded in assistant API metadata; None omits it, so resume uses the user's default
    input_toks=0, # `input_tokens` recorded in assistant usage, e.g. an estimate of the context so far
    **kwargs, # Extra or overriding envelope fields, e.g. `isCompactSummary=True`
):
    "A transcript record for one conversation message, ready for `save_sess`"
    uid = uid or str(uuid.uuid4())
    if isinstance(content, list):
        content = [{k:v for k,v in b.items() if k!='cache_control'} if isinstance(b, dict) else b for b in content]
        if role=='user' and content and all(isinstance(b, dict) and b.get('type')=='text' for b in content): content = ''.join(b['text'] for b in content)
    msg = dict(type='message', role=role, content=content)
    r = dict(type=role, uuid=uid, parentUuid=None, sessionId=None, timestamp=ts or _now(), cwd=str(Path(cwd).expanduser().resolve()),
        version=CC_VERSION, gitBranch='HEAD', isSidechain=False, userType='external', entrypoint='cli', session_id=None, message=msg)
    if role=='user' and isinstance(content, list) and (trs := [b for b in content if isinstance(b, dict) and b.get('type')=='tool_result']):
        c = trs[-1]['content']
        r['toolUseResult'] = c if isinstance(c, list) else [dict(type='text', text=c)]
    if role=='assistant':
        tu = isinstance(content, list) and any(isinstance(b, dict) and b.get('type')=='tool_use' for b in content)
        r['requestId'] = 'req_'+stable_uuid(f'{uid}:req').replace('-', '')[:24]
        usage = dict(input_tokens=input_toks, output_tokens=_est_toks(content), cache_creation_input_tokens=0, cache_read_input_tokens=0)
        msg.update(id='msg_'+stable_uuid(f'{uid}:msg').replace('-', '')[:24],
            stop_reason='tool_use' if tu else 'end_turn', stop_sequence=None, stop_details=None, usage=usage)
        if model: msg['model'] = model
    return dict(r, **kwargs)

# %% ../nbs/00_session.ipynb #882a017d
def _chain(recs, sid, prev, ts, used=()):
    "Chain `recs` for session `sid` after uuid `prev`, refusing duplicate uuids (a cycle on disk otherwise)"
    seen = set(used)
    for r in recs:
        if 'uuid' not in r: continue   # bookkeeping records (last-prompt, mode, ...) ride along unchained
        if (u := r['uuid']) in seen: raise ValueError(f'duplicate record uuid {u}')
        seen.add(u)
        r['sessionId'],r['parentUuid'],prev = sid,prev,u
        if ts: r['timestamp'] = _now() if ts is True else ts
        if 'session_id' in r: r['session_id'] = sid

def save_sess(
    recs, # Records in conversation order, e.g. from `mk_rec`
    sid=None, # Session id; a fresh uuid if None
    cwd=None, # Project directory; the current directory if None
    ts=None, # If given, stamp every record's timestamp: True for the current time, or an ISO8601 string
):
    "Chain `recs`, write them as session `sid` for the project at `cwd`, and return `sid`"
    sid = sid or str(uuid.uuid4())
    _chain(recs, sid, None, ts)
    f = sess_file(sid, cwd or '.')
    f.parent.mkdir(parents=True, exist_ok=True)
    f.write_text(''.join(xdumps(r)+'\n' for r in recs))
    return sid

# %% ../nbs/00_session.ipynb #100586c9
def append_sess(
    recs, # Records to append, e.g. a munged template round
    sid=None, # Session to append to; `cur_sess()` if None
    cwd=None, # Project directory; the current directory if None
    ts=None, # If given, stamp each appended record's timestamp: True for the current time, or an ISO8601 string
):
    "Chain `recs` onto the tail of session `sid` and append them to its transcript, returning `sid`"
    sid = sid or cur_sess(cwd)
    old = [r['uuid'] for r in load_sess(sid, cwd) if 'uuid' in r]
    _chain(recs, sid, last(old), ts, old)
    with sess_file(sid, cwd).open('a') as f: f.writelines(xdumps(r)+'\n' for r in recs)
    return sid

# %% ../nbs/00_session.ipynb #0e3c39a2
def msgs2recs(
    msgs, # Anthropic-style messages: dicts with `role` and `content`
    key='', # Salt: the same messages and key give the same ids
    cwd='.', # Project directory recorded in the envelopes
    ts='2026-01-01T00:00:00.000Z', # Timestamp for every record
    model='claude-sonnet-4-6', # Recorded in assistant API metadata; None omits it, so resume uses the user's default
    **kwargs, # Extra envelope fields for every record, e.g. `entrypoint`
):
    "Deterministic transcript records for `msgs`, one record per message"
    out,tot = [],0
    for i,m in enumerate(msgs):
        out.append(mk_rec(m['role'], m['content'], cwd=cwd, uid=stable_uuid(f'{key}:{i}:{canon(m)}'), ts=ts, model=model, input_toks=tot, **kwargs))
        tot += _est_toks(m['content'])
    return out

# %% ../nbs/00_session.ipynb #94786c44
@delegates(msgs2recs)
def msgs2sess(
    msgs, # Anthropic-style messages: dicts with `role` and `content`
    key='', # Salt: the same messages and key give the same session id
    cwd='.', # Project directory the session is filed under
    extra=None, # Records appended after the messages, e.g. from `mk_deferred`
    **kwargs
):
    "Write `msgs` as a resumable session with a content-stable id, returning the sid"
    sid = stable_uuid(f'{key}:{canon(msgs)}:{canon(extra or [])}')
    return save_sess(msgs2recs(msgs, key=sid, cwd=cwd, **kwargs)+list(extra or []), sid, cwd)

# %% ../nbs/00_session.ipynb #a891d415
def sess_id(recs):
    "The session id in transcript records `recs`"
    return first(r.get('sessionId') for r in recs if r.get('sessionId'))

# %% ../nbs/00_session.ipynb #5cab1ea0
def _fork_title(recs):
    "The source's last custom or AI title, else its first user prompt line"
    for k in ('customTitle','aiTitle'):
        if t := last((r[k] for r in recs if r.get(k)), None): return t
    return first((rec_txt(r).partition('\n')[0] for r in recs if r.get('type')=='user'), 'Forked session')

def fork_session(
    sid=None, # Session id or unique prefix to fork; the current session if None
    cwd=None, # Project directory; the current directory if None
    up_to=None, # Record uuid to cut at (inclusive); the whole transcript if None
    title=None, # Fork title; the source's `_fork_title` plus ' (fork)' if None
):
    "Fork a session natively: fresh session id and record uuids, rebuilt parent chain; returns the new sid"
    recs = load_recs(sess_file(sid, cwd))
    ssid = sess_id(recs)
    keep = [r for r in recs if r.get('type') in ('user','assistant','attachment','system','progress')
        and isinstance(r.get('uuid'), str) and not r.get('isSidechain')]
    if up_to:
        idx = first((i for i,r in enumerate(keep) if r['uuid']==up_to), None)
        if idx is None: raise ValueError(f'uuid not in transcript: {up_to}')
        keep = keep[:idx+1]
    ids = {r['uuid']: str(uuid.uuid4()) for r in keep}
    by_id = {r['uuid']: r for r in keep}
    fsid,now = str(uuid.uuid4()),_now()
    writable = [r for r in keep if r.get('type')!='progress']
    out = []
    for i,r in enumerate(writable):
        pid = r.get('parentUuid')
        while pid and by_id.get(pid, {}).get('type')=='progress': pid = by_id[pid].get('parentUuid')
        f = {**r, 'uuid': ids[r['uuid']], 'parentUuid': ids.get(pid), 'sessionId': fsid, 'isSidechain': False}
        f['timestamp'] = now if i==len(writable)-1 else r.get('timestamp', now)
        f['logicalParentUuid'] = ids.get(lp, lp) if (lp := r.get('logicalParentUuid')) else None
        f['forkedFrom'] = dict(sessionId=ssid, messageUuid=r['uuid'])
        for k in ('teamName','agentName','slug','sourceToolAssistantUUID'): f.pop(k, None)
        out.append(f)
    reps = [x for r in recs if r.get('type')=='content-replacement' and r.get('sessionId')==ssid for x in (r.get('replacements') or [])]
    if reps: out.append(dict(type='content-replacement', sessionId=fsid, replacements=reps, uuid=str(uuid.uuid4()), timestamp=now))
    out.append(dict(type='custom-title', sessionId=fsid, customTitle=title or f'{_fork_title(recs)} (fork)', uuid=str(uuid.uuid4()), timestamp=now))
    p = sess_dir(cwd)/f'{fsid}.jsonl'
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(''.join(json.dumps(obj2dict(r), separators=(',',':'))+'\n' for r in out))
    return fsid

# %% ../nbs/00_session.ipynb #05433084
def mk_tu(
    name, # Tool name, as the transcript records it
    input=None, # Tool arguments
    tid=None, # tool_use id; random if None
):
    "A `tool_use` content block"
    return dict(type='tool_use', id=tid or 'toolu_'+uuid.uuid4().hex[:24], name=name, input=input or {})

def mk_tr(
    tu, # The `tool_use` block being answered
    content, # The tool's output
):
    "The `tool_result` content block answering `tu`"
    return dict(type='tool_result', tool_use_id=tu['id'], content=content)

def tool_turn(
    prompt, # The user request
    name, # Tool name
    input, # Tool arguments
    output, # Tool result
    answer, # The assistant's closing text
    **kwargs, # Passed to each `mk_rec`, e.g. `cwd`
):
    "A complete synthetic tool-use turn, as four records ready for `save_sess`"
    tu = mk_tu(name, input)
    return [mk_rec('user', prompt, **kwargs), mk_rec('assistant', [tu], **kwargs),
        mk_rec('user', [mk_tr(tu, output)], **kwargs), mk_rec('assistant', [dict(type='text', text=answer)], **kwargs)]

# %% ../nbs/00_session.ipynb #2c65fe8c
def mk_deferred(
    tu, # The pending `tool_use` block dict
    cwd='.', # Project directory recorded in the envelope
    uid=None, # Record uuid; random if None
    ts='2026-01-01T00:00:00.000Z', # Timestamp recorded in the envelope
):
    "A `hook_deferred_tool` attachment record marking `tu` as deferred, ready for `save_sess`"
    return dict(type='attachment', uuid=uid or str(uuid.uuid4()), parentUuid=None, sessionId=None, isSidechain=False,
        timestamp=ts, userType='external', cwd=str(Path(cwd).expanduser().resolve()), version=CC_VERSION, gitBranch='HEAD',
        attachment=dict(type='hook_deferred_tool', toolUseID=tu['id'], toolName=tu['name'], toolInput=tu.get('input', {}),
            hookName='settings', hookEvent='PreToolUse', permissionMode='default'))

# %% ../nbs/00_session.ipynb #b8610c76
def load_sess(
    sid=None, # Session id; the current session if None
    cwd=None, # Project directory; the current directory if None
):
    "The records of session `sid`, as an `L` of attribute-access dicts"
    return load_recs(sess_file(sid, cwd))

# %% ../nbs/00_session.ipynb #0680dea4
def prefix_tools(
    msgs, # Anthropic-style messages
    prefix, # Stub name prefix, e.g. 'mcp__probe__'
    skip=(), # Native tool names to leave unqualified, e.g. 'WebSearch'
):
    "Copy of `msgs` with client `tool_use` names qualified by `prefix`"
    def _fix(b):
        if not (isinstance(b, dict) and b.get('type')=='tool_use'): return b
        nm = b.get('name','')
        if not nm or nm.startswith('mcp__') or nm in skip: return b
        return dict(b, name=prefix+nm)
    return [dict(m, content=[_fix(b) for b in m['content']]) if isinstance(m.get('content'), list) else m for m in msgs]
